global using NUnit.Framework;
global using auction_service.Service;
global using auction_service.Models;
global using auction_service.Controllers;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System;
global using Microsoft.AspNetCore.Mvc;
global using System.Net;
global using Moq;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Configuration;
global using Moq;
global using MongoDB;
global using MongoDB.Driver;

