version: '3.7' 

services: 
  customer-service: 
    image: nicolaiskat/eksamen-customer-service:latest 
    expose: 
      - "80"   
  item-service: 
    image: nicolaiskat/eksamen-item-service:latest 
    expose: 
      - "80"   
  nginx: 
    image: nginx:latest 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on: 
      - customer-service
      - item-service 
    ports:
      - "4000:4000"

  mongodb_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: