version: '3.7' 

services: 
  bidding-publisher: 
    image: nicolaiskat/eksamen-bidding-publisher:latest
    ports: 
      - "80" 
    environment: 
      - AuctionBrokerHost=rabbitmq-dev 
    depends_on: 
      - rabbitmq-dev  

  item-service: 
    image: nicolaiskat/eksamen-item-service:latest 
    expose: 
      - "80" 
    environment:
      - MongoConnectionString=mongodb://admin:password@mongodb:27017/?authSource=admin&serverSelectionTimeoutMS=3000&connectTimeoutMS=3000
    depends_on:
      - mongodb

  nginx: 
    image: nginx:latest 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on: 
      - item-service 
      - bidding-publisher 
    ports:
      - "4000:4000"

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: