version: '3.7' 

services: 
  bidding-publisher: 
    image: eksamen-bidding-service:dev
    ports: 
      - "80" 
    environment: 
      - AuctionBrokerHost=rabbitmq-dev 
    depends_on: 
      - rabbitmq-dev 
      - auction-service 

  auction-service: 
    image: eksamen-auction-service:dev
    ports: 
      - "80" 
    environment:
      - MongoConnectionString=mongodb://admin:password@mongodb:27017/?authSource=admin&serverSelectionTimeoutMS=3000&connectTimeoutMS=3000
      - AuctionBrokerHost=rabbitmq-dev 
    depends_on: 
      - rabbitmq-dev  
      - mongodb

  item-service: 
    image: eksamen-item-service:dev 
    expose: 
      - "80" 
    environment:
      - MongoConnectionString=mongodb://admin:password@mongodb:27017/?authSource=admin&serverSelectionTimeoutMS=3000&connectTimeoutMS=3000
    depends_on:
      - mongodb

  nginx: 
    image: nginx:latest 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on: 
      - item-service 
      - bidding-publisher 
      - auction-service 
    ports:
      - "4000:4000"
      
  rabbitmq-dev: 
    image: rabbitmq:management 
    ports: 
      - "15672:15672" 
      - "5672:5672"

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: