name: Automatic test on bidding-service

on:
  push:
    branches: [ "develop" ]
    paths:
      - BiddingHandler/**

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  IMAGE_NAME: eksamen-bidding-service:latest
  PATH_TO_IMAGE: ./BiddingHandler/BidddingHandler
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: |
          cd ./BiddingHandler/BiddingHandlerTest
          dotnet restore
      - name: Build
        run: |
          cd ./BiddingHandler/BiddingHandlerTest
          dotnet build --configuration Release --no-restore
      - name: Test
        run: |
          cd ./BiddingHandler
          dotnet test --no-restore --verbosity normal
        
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${DOCKER_USER}
          password: ${DOCKER_TOKEN}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          username: ${DOCKER_USER}
          password: ${GITHUB_TOKEN}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ${PATH_TO_IMAGE}
          tags: ${DOCKER_USER}/{IMAGE_NAME}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
        
