name: Push Bidding Service To Docker
on:
  pull_request:
    branches: [release]
        
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  IMAGE_NAME: eksamen-bidding-service:latest
  PATH_TO_IMAGE: ./BiddingHandler/BidddingHandler
  
jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${DOCKER_USER}
          password: ${DOCKER_TOKEN}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          username: ${DOCKER_USER}
          password: ${GITHUB_TOKEN}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ${PATH_TO_IMAGE}
          tags: ${DOCKER_USER}/{IMAGE_NAME}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
